# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'miniProjectTalpor' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for miniProjectTalpor
  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.15.0'

  platform :ios, '9.0'
end
